// Bundles index.html's controls, style.css and sketch.js into one file,
// p5-editor/sketch.js, that pastes straight into the p5.js web editor's
// sketch.js tab (set the editor to p5 2.3.3). Run: node build-p5.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const here = (f) => new URL(f, import.meta.url);
const html = readFileSync(here('index.html'), 'utf8');
const css = readFileSync(here('style.css'), 'utf8');
const sketch = readFileSync(here('sketch.js'), 'utf8');

// Everything in <body> before the sketch's own <script> tag.
const body = html.slice(html.indexOf('<body>') + 6, html.indexOf('<script src="sketch.js">')).trim();

const out = `// Sonar text editor: one-file build for the p5.js web editor.
// Paste this whole file into sketch.js at https://editor.p5js.org/?version=2.3.3
// (needs p5 2.x). It adds its own controls and styles, so index.html and
// style.css can stay as the editor's defaults.
// Generated by build-p5.mjs from index.html, style.css and sketch.js; edit those.

(() => {
  const css = ${JSON.stringify(css)};
  const html = ${JSON.stringify(body)};
  const inject = () => {
    const style = document.createElement('style');
    style.textContent = css;
    document.head.append(style);
    document.body.insertAdjacentHTML('afterbegin', html);
  };
  if (document.body) inject();
  else document.addEventListener('DOMContentLoaded', inject);
})();

${sketch}`;

mkdirSync(here('p5-editor/'), { recursive: true });
writeFileSync(here('p5-editor/sketch.js'), out);
console.log(`p5-editor/sketch.js: ${(out.length / 1024).toFixed(1)} KB`);
