// Bundles each page's markup, style.css and scripts into one file that pastes
// straight into the p5.js web editor's sketch.js tab (set the editor to p5
// 2.3.3). Run: node build-p5.mjs
//   p5-editor/sketch.js         the tool with its controls (index.html)
//   p5-editor/random-sketch.js  no controls; every letter re-rolls the look (random/)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const here = (f) => new URL(f, import.meta.url);
const read = (f) => readFileSync(here(f), 'utf8');
const css = read('style.css');

function bundle({ page, scripts, out, about }) {
  const html = read(page);
  // Everything in <body> before the first <script> tag.
  const body = html.slice(html.indexOf('<body>') + 6, html.indexOf('<script', html.indexOf('<body>'))).trim();
  const code = scripts.map((f) => read(f)).join('\n\n');

  const text = `// Sonar text editor${about}: one-file build for the p5.js web editor.
// Paste this whole file into sketch.js at https://editor.p5js.org/?version=2.3.3
// (needs p5 2.x). It adds its own markup and styles, so index.html and
// style.css can stay as the editor's defaults.
// Generated by build-p5.mjs from ${[page, 'style.css', ...scripts].join(', ')}; edit those.

(() => {
  const css = ${JSON.stringify(css)};
  const html = ${JSON.stringify(body)};
  const inject = () => {
    const style = document.createElement('style');
    style.textContent = css;
    document.head.append(style);
    document.body.insertAdjacentHTML('afterbegin', html);
  };
  if (document.body) inject();
  else document.addEventListener('DOMContentLoaded', inject);
})();

${code}`;

  writeFileSync(here(out), text);
  console.log(`${out}: ${(text.length / 1024).toFixed(1)} KB`);
}

mkdirSync(here('p5-editor/'), { recursive: true });
bundle({ page: 'index.html', scripts: ['sketch.js'], out: 'p5-editor/sketch.js', about: '' });
bundle({
  page: 'random/index.html',
  scripts: ['sketch.js', 'random/random.js'],
  out: 'p5-editor/random-sketch.js',
  about: ', random',
});
